#!/bin/sh

# This is meant to be used as a shell script invoked in a cron for backing up
# the current state of the conf/ folder in zeus' install path.

# provide correct path to override the following two positional arguments                                                                                          [122/1848]

CMD=`basename "$0"`
CONF=${1:-~/zeus-conf}; CONF=`readlink -f $CONF`
BKUP=${2:-~/zeus-bkup}; BKUP=`readlink -f $BKUP`
REV=${3:HEAD}

if [ "$CONF" == "$BKUP" ]; then
    echo "CONF=$CONF cannot match BKUP=$BKUP!"
    exit 1
fi
if ! hash git 2> /dev/null; then
    echo "git not installed!"
    exit 1
fi
if ! hash rsync 2> /dev/null; then
    echo "rsync not installed!"
    exit 1
fi

backup() {
    mkdir -p $BKUP
    rsync -rav --delete --exclude=.git/ $CONF/ $BKUP/
    cd $BKUP
    if [ "true" != "`git rev-parse --is-inside-work-tree 2> /dev/null`" ]; then
        git init
    fi
    git add .
    MSG="`git status --short`"
    if [ "$MSG" ]; then
        git commit -m "$MSG"
    fi
}

restore() {
    cd $BKUP
    git clean -xfd
    git reset --hard $REV
    rsync -rav --delete --exclude=.git/ $BKUP/ $CONF/
}

case "$CMD" in
    zeus-backup)
        backup
        ;;
    zeus-restore)
        restore
        ;;
    *)
        echo "unknown CMD=$CMD!"
        exit 1
        ;;
esac
